# Generated by Django 5.1.1 on 2024-09-22 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(default='', max_length=255)),
                ('last_name', models.CharField(default='', max_length=255)),
                ('course', models.CharField(default='', max_length=255)),
                ('registration_number', models.CharField(default='', max_length=255)),
                ('registration_date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
