# Generated by Django 5.1.2 on 2024-10-23 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_rename_category_name_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='myapp.category'),
        ),
    ]
