# Generated by Django 5.1.2 on 2024-11-25 16:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_registerbook_alter_eventapplication_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='email_verified',
            new_name='is_email_verified',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='verification_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
