# Generated by Django 5.1.2 on 2024-12-15 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_room_roombooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(choices=[('room_76', 'Room 76'), ('room_14', 'Room 14'), ('room_45', 'Room 45')], max_length=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('small', 'Small Room (1-50 people)'), ('medium', 'Medium Room (51-200 people)'), ('large', 'Large Room (201-500 people)')], max_length=20),
        ),
    ]
