# Generated by Django 5.1.2 on 2024-12-15 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_room_name_alter_room_room_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='price_per_hour',
            new_name='price',
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
