# Generated by Django 5.1.2 on 2024-12-15 11:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_rename_price_per_hour_room_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(choices=[('room_76', 'Room 76'), ('room_14', 'Room 14'), ('room_45', 'Room 45')], max_length=10, unique=True),
        ),
    ]
