# Generated by Django 5.1.2 on 2024-12-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_alter_room_description_alter_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(choices=[('room_43', 'Room 43'), ('room_45', 'Room 45'), ('room_76', 'Room 76'), ('room_50', 'Room 50')], max_length=10, unique=True),
        ),
    ]
