# Generated by Django 5.1.2 on 2024-12-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_room_is_requested_alter_room_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(choices=[('small', 'Small Room (1-50 people)'), ('medium', 'Medium Room (51-200 people)'), ('large', 'Large Room (201-500 people)')], max_length=10, unique=True),
        ),
    ]
