# Generated by Django 5.1.2 on 2024-12-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_alter_room_name_alter_room_room_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.CharField(default='no message', max_length=255)),
            ],
        ),
    ]
