# Generated by Django 5.1.2 on 2024-12-21 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_rename_message_message_message_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message_content',
            new_name='description',
        ),
    ]
