# Generated by Django 5.1.2 on 2024-12-29 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_remove_product_image_remove_product_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
